---
- name: Ensure /etc/ansible directory exists.
  file:
    path: /etc/ansible
    state: directory
  when: mac_dev_execute == true
  become: yes

- name: Symlink /usr/local/etc/ansible to /etc/ansible.
  file:
    src: /etc/ansible
    path: /usr/local/etc/ansible
    state: link
  when: mac_dev_execute == true
